dataset_config:
    data_dir: /Data/gowalla
    data_format: txt
    separator: ' '
    train_data: train.txt
    test_data: test.txt

model_config:
    num_negs: 64
    max_his: 100
    embedding_dim: 128
    neg_sampler: 0
    tile_size: 512
    refresh_interval: 8192
    embedding_dropout: 0
    similarity_score: dot
    loss: PairwiseLogisticLoss
    metrics: ['Recall(k=20)', 'Recall(k=50)', 'NDCG(k=20)', 'NDCG(k=50)', 'HitRate(k=20)', 'HitRate(k=50)']
    optimizer: sgd
    milestones: [10]
    learning_rate: 1.e-2
    clip_val: 0.1
    embedding_regularizer: 1.e-7
    net_regularizer: 0
    net_dropout: 0
    epochs: 8
    eval_interval: 10
    seed: 2022